import { EventEmitter } from 'events';

class EventBus extends EventEmitter {}

export const eventBus = new EventBus();

// Core Event Names
export const EVENTS = {
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  PATIENT_CHECKED_IN: 'PATIENT_CHECKED_IN',
  QUEUE_TOKEN_CREATED: 'QUEUE_TOKEN_CREATED',
  CONSULTATION_STARTED: 'CONSULTATION_STARTED',
  CONSULTATION_COMPLETED: 'CONSULTATION_COMPLETED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_DISPENSED: 'PRESCRIPTION_DISPENSED',
  LAB_TEST_REQUESTED: 'LAB_TEST_REQUESTED',
  LAB_RESULT_COMPLETED: 'LAB_RESULT_COMPLETED',
};
